alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'

alias git-diff='git diff --color-words'

alias updgrade='sudo aptitude update && sudo aptitude upgrade'
alias kissfm='mplayer -playlist http://www.crosshost.com.br/cbs/kiss/ouvir.m3u'
alias q='exit'
alias h='history'
alias ..='cd ..'
alias rmtemp='rm -f *~'
alias off='sudo shutdown -h now'
alias srcrc='source ~/.bashrc'

alias hdabelb='sudo mount -t vfat /dev/sdb1 /media/hdabel -o uid=1000 -o iocharset=utf8'
alias hdabelc='sudo mount -t vfat /dev/sdc1 /media/hdabel -o uid=1000 -o iocharset=utf8'
alias hdabeld='sudo mount -t vfat /dev/sdd1 /media/hdabel -o uid=1000 -o iocharset=utf8'
alias hdabele='sudo mount -t vfat /dev/sde1 /media/hdabel -o uid=1000 -o iocharset=utf8'
alias hdabelf='sudo mount -t vfat /dev/sdf1 /media/hdabel -o uid=1000 -o iocharset=utf8'

alias ls='ls -h --color=auto'
alias ll='ls -l --group-directories-first'
alias la='ls -A'
alias lla='ll -A'
alias lsdir='ls -d */'
alias lx='ls -lXB'
alias lsize='ls -lSr'
alias ltime='ls -ltcr'
alias ldate='ls -ltr'
alias lr='ls -lR'
alias tree='tree -Csu'
alias grep='grep --color'

alias df='df -h'
alias du='du -h'
alias dusort='du -s -BM * | sort -n'
alias free='free -m'
alias cache_clear='sudo sh -c "sync; echo 3 > /proc/sys/vm/drop_caches" '

alias editbash='vim ~/.bashrc'
alias editalias='vim ~/.bashaliases'

alias lsmp3='find . -name "*.mp3" | sort'
alias mkthislst='lsmp3 > this.lst'
alias playmp3='mpg123 -C'
alias randomplay='mpg123 -CZ'
alias randomplaythis='mpg123 -CZ --list this.lst'
alias playthis='mpg123 -C --list this.lst'

alias hdmimplayer='mplayer -ao alsa:device=hw=2.3'
alias vaapimplayer='mplayer -vo vaapi:gl -va vaapi'
alias ffta='sudo VisualBoyAdvance -4 -N ~/FFTA/Final\ Fantasy\ Tactics\ Advance.GBA'

alias pdfwidth='xpdf -z width'
alias pdfpage='xpdf -z page'

alias renamevtv='rename .[VTV]. . *'
alias ravenespeak='espeak -p0 -s120 "Quoth the raven: Nevermore"'
